parameters:
#    kuborgh_auphonic.example.class: Kuborgh\AuphonicBundle\Example

services:
#    kuborgh_auphonic.example:
#        class: %kuborgh_auphonic.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
